# Generated by Django 3.1.7 on 2021-10-30 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0001_initial'),
        ('producto', '0008_auto_20211030_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_stock_dia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 14, 43, 58, 607111), unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presentacion.presentacion'),
        ),
    ]
