# Generated by Django 3.1.7 on 2021-10-30 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20211030_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_stock_dia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 17, 39, 55, 670600), unique=True),
        ),
    ]
