# Generated by Django 3.1.7 on 2021-10-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resetpass',
            field=models.BooleanField(default=False),
        ),
    ]
