# Generated by Django 3.1.7 on 2021-10-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_venta_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_servicios_duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(blank=True, null=True)),
                ('hora_reserva', models.IntegerField(default=0)),
                ('minuto_reserva', models.IntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.detalle_servicios')),
            ],
            options={
                'verbose_name': 'detalle_servicio_duracion',
                'verbose_name_plural': 'detalle_servicio_duraciones',
                'db_table': 'detalle_servicio_duracion',
            },
        ),
    ]
